version: '3'

volumes: 
  dbdata:
  webdata:
  

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8443:8443
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=member
      - DB_USER=user
      - DB_PASSWORD=a.1234567
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
        - webdata:/code

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: a.1234567
      POSTGRES_DB: member
    ports:
      - 5432:5432
    volumes:
        - dbdata:/var/lib/postgresql/data/

